CREATE TABLE BOOK_USER
(
  LOGINID   VARCHAR2(100 BYTE)                  NOT NULL,
  LOGINPW   VARCHAR2(100 BYTE)                  NOT NULL,
  ENTDT     DATE,
  LOGINDT   DATE,
  LOGOUTDT  DATE
);

CREATE UNIQUE INDEX BOOK_USER_PK ON BOOK_USER (LOGINID);

ALTER TABLE BOOK_USER ADD (
  CONSTRAINT BOOK_USER_PK
  PRIMARY KEY
  (LOGINID)
  USING INDEX BOOK_USER_PK
  ENABLE VALIDATE);
  
CREATE TABLE BOOK_MARK
(
  LOGINID    VARCHAR2(100 BYTE)                 NOT NULL,
  TITLE      VARCHAR2(200 BYTE)                 NOT NULL,
  ENTDT      DATE,
  THUMBNAIL  VARCHAR2(250 BYTE),
  URL        VARCHAR2(250 BYTE)
);

CREATE UNIQUE INDEX BOOK_MARK_PK ON BOOK_MARK (LOGINID, TITLE);

ALTER TABLE BOOK_MARK ADD (
  CONSTRAINT BOOK_MARK_PK
  PRIMARY KEY
  (LOGINID, TITLE)
  USING INDEX BOOK_MARK_PK
  ENABLE VALIDATE);
  
CREATE TABLE BOOK_HISTORY
(
  LOGINID  VARCHAR2(100 BYTE)                   NOT NULL,
  TITLE    VARCHAR2(200 BYTE)                   NOT NULL,
  ENTDT    DATE
);

CREATE UNIQUE INDEX BOOK_HISTORY_PK ON BOOK_HISTORY (LOGINID, TITLE);

ALTER TABLE BOOK_HISTORY ADD (
  CONSTRAINT BOOK_HISTORY_PK
  PRIMARY KEY
  (LOGINID, TITLE)
  USING INDEX BOOK_HISTORY_PK
  ENABLE VALIDATE);